name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install
        run: |
          yarn install
      - name: run Lighthouse CI
        run: |
          yarn install -g @lhci/cli@0.6.x
          lhci autorun