name: Run test

on:
  pull_request:
  push:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add dependencies
        run: |
          yarn install
      - name: Run build
        run: |
          yarn build